version: '2'
services:
    wboard-app:
        image: wboard
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://wboard-postgresql:5432/wBoard
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=wboard-elasticsearch:9300
        ports:
            - 8080:8080
    wboard-postgresql:
        extends:
            file: postgresql.yml
            service: wboard-postgresql
    wboard-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: wboard-elasticsearch
